---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/posts
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: src/content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page
- type: heading
  label: Single Pages
- type: document
  path: src/content/faq.md
  label: FAQ
- type: document
  path: src/content/turnip-prices.md
  label: Turnip Prices
upload_dir: personal-website
public_path: https://res.cloudinary.com/zena/image/upload/c_limit,h_512,w_512
front_matter_path: https://res.cloudinary.com/zena/image/upload/personal-website
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
